version: '3.7'

services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weshop
  backend:
    build: ./backend
    # command: python /usr/local/weshop-backend/manage.py runserver 0.0.0.0:8001
    command: gunicorn Weshop.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./backend:/usr/local/weshop-backend
      - media_volume:/usr/local/weshop-backend/media
    expose:
      - 8001
    environment:
      - SECRET_KEY=qs(qih1plsr&9%^mnpl($pixljb^b10j#ew_i$xqe5yg$$jsyo
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=weshop
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - media_volume:/usr/local/weshop-backend/media
    ports:
      - 3001:8080
    environment:
      - OUT_PORT=8080
    depends_on:
      - backend

volumes:
  postgres_data:
  media_volume: