version: '3'

services:
  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weshop
  django:
    build: .
    image: yeungzed/weshop_backend_django:latest
    volumes:
      - ./:/usr/local/weshop-backend
      - static_volume:/usr/local/weshop-backend/static/
      - media_volume:/usr/local/weshop-backend/media/
    expose:
      - 8001
    environment:
      - SECRET_KEY=qs(qih1plsr&9%^mnpl($pixljb^b10j#ew_i$xqe5yg$$jsyo
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=weshop
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: yeungzed/weshop_backend_nginx:latest
    volumes:
      - static_volume:/usr/local/weshop-backend/static/
      - media_volume:/usr/local/weshop-backend/media/
    environment:
      - PORT=80
    ports:
      - 8081:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: