# Generated by Django 2.1.5 on 2019-02-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190209_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_name',
            new_name='shipping_fullname',
        ),
    ]
