# Generated by Django 2.1.5 on 2019-02-09 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('stripe_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_status', models.CharField(choices=[('succeeded', 'succeeded'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=30)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('customer_message', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shipping_name', models.CharField(blank=True, max_length=30)),
                ('shipping_address1', models.CharField(blank=True, max_length=30)),
                ('shipping_address2', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=30)),
                ('shipping_state', models.CharField(blank=True, max_length=30)),
                ('shipping_country', models.CharField(blank=True, max_length=30)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=30)),
                ('shipping_phone', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
            options={
                'verbose_name': 'order product',
                'verbose_name_plural': 'order products',
            },
        ),
    ]
